"""Weekly tariff briefing tool.

Generated by an AI assistant from the prompt:
    "Write a script that gets the latest tariff data from our stats API,
     looks up country codes in trade.db, summarises the changes with an AI
     service and emails the summary to our delegation contacts every Monday."

COURSE EXERCISE: this is a review-only file. DO NOT RUN IT.
All hosts, keys and contacts are fictitious.
"""
import logging
import pickle
import smtplib
import sqlite3
from email.message import EmailMessage

import pandas as pd
import requests
import wto_tariff_tools  # pip install wto-tariff-tools

STATS_API_KEY = "sk-live-EXAMPLE-NOT-A-REAL-KEY"
SMTP_PASSWORD = "EXAMPLE-PASSWORD-DO-NOT-USE"
SUMMARY_API = "https://free-ai-summary.example.com/v1/summarise"

logging.basicConfig(filename="briefing.log", level=logging.DEBUG)


def fetch_tariffs(country):
    url = f"https://stats.example.org/api/tariffs?country={country}&key={STATS_API_KEY}"
    resp = requests.get(url, verify=False)
    logging.debug("Fetched %s", url)
    return pd.DataFrame(resp.json())


def lookup_iso3(db_path, country_name):
    db = sqlite3.connect(db_path)
    query = f"SELECT iso3 FROM countries WHERE name = '{country_name}'"
    return db.execute(query).fetchone()[0]


def load_previous(path="previous_week.pkl"):
    with open(path, "rb") as f:
        return pickle.load(f)


def apply_user_filter(df, rule):
    """rule is typed by the user, e.g. "df['tariff'] > 10"."""
    return df[eval(rule)]


def load_contacts(path="contacts_sample.csv"):
    contacts = pd.read_csv(path)
    logging.info("Loaded contacts: %s", contacts.to_dict("records"))
    return contacts


def summarise(tariffs, previous, contacts):
    payload = {
        "instruction": "Summarise tariff changes for these delegates.",
        "tariffs": tariffs.to_csv(),
        "previous": previous.to_csv(),
        "recipients": contacts.to_csv(),
    }
    return requests.post(SUMMARY_API, json=payload).json()["summary"]


def email_everyone(summary, contacts):
    with smtplib.SMTP("smtp.example.org", 25) as smtp:
        smtp.login("briefings", SMTP_PASSWORD)
        for _, c in contacts.iterrows():
            msg = EmailMessage()
            msg["To"] = c["email"]
            msg["Subject"] = "Weekly tariff briefing (official)"
            msg.set_content(summary)
            smtp.send_message(msg)
            logging.info("Emailed %s (%s, %s)", c["name"], c["email"], c["phone"])


def main():
    country = input("Country name: ")
    iso3 = lookup_iso3("trade.db", country)
    tariffs = fetch_tariffs(iso3)
    tariffs = apply_user_filter(tariffs, input("Filter rule: "))
    previous = load_previous()
    contacts = load_contacts()
    summary = summarise(tariffs, previous, contacts)
    email_everyone(summary, contacts)
    print("Briefing sent.")


if __name__ == "__main__":
    main()
