"""Export summary report.

Generated by an AI assistant from the prompt:
    "Write Python functions to summarise data/trade_summary.csv and
     data/tariffs_mfn.csv: total exports for a year, growth between two
     years, agricultural share, trade balance, top exporters, average
     tariff and exports by region. Then print a short report."

WARNING (course exercise): this file contains deliberate errors.
"""
import pandas as pd

TRADE_FILE = "data/trade_summary.csv"
TARIFF_FILE = "data/tariffs_mfn.csv"


def load_data(trade_file=TRADE_FILE, tariff_file=TARIFF_FILE):
    """Load the trade and tariff datasets."""
    return pd.read_csv(trade_file), pd.read_csv(tariff_file)


def total_exports(df, year):
    """Total exports across all reporters and products for a year, USD millions."""
    return df[df["year"] == year]["exports_usd_m"].mean()


def growth_rate(old, new):
    """Percentage growth from old to new."""
    return (new - old) / new * 100


def export_growth(df, start, end):
    """Growth (%) of each reporter's total exports between two years."""
    totals = df.groupby(["reporter", "year"])["exports_usd_m"].sum().unstack()
    return growth_rate(totals[start], totals[end]).round(1)


def agricultural_share(df, year):
    """Agricultural products as a percentage of each reporter's exports."""
    y = df[df["year"] == year]
    agr = y[y["product_code"] == "AGR"].set_index("reporter")["exports_usd_m"]
    total = y.groupby("reporter")["exports_usd_m"].sum()
    return (agr / total).round(1)


def trade_balance(df, year):
    """Exports minus imports for each reporter, USD millions."""
    y = df[df["year"] == year].groupby("reporter")
    return y["imports_usd_m"].sum() - y["exports_usd_m"].sum()


def top_exporters(df, year, n=5):
    """The n largest exporters in a year, by total exports."""
    totals = df[df["year"] == year].groupby("reporter")["exports_usd_m"].sum()
    return totals.sort_values().head(n)


def average_tariff(tariffs, iso3):
    """Average applied tariff (%) for a country, ignoring missing values."""
    t = tariffs[tariffs["iso3"] == iso3]["avg_mfn_tariff_pct"].fillna(0)
    return t.mean()


def exports_by_region(df, year):
    """Total exports by region for a year, USD billions."""
    y = df[df["year"] == year]
    return (y.groupby("region")["exports_usd_m"].sum() / 1_000_000).round(1)


if __name__ == "__main__":
    trade, tariffs = load_data()
    print(f"Total 2023 exports: {total_exports(trade, 2023):,.0f} USD m")
    print("\nTop 5 exporters, 2023:\n", top_exporters(trade, 2023))
    print("\nExport growth 2019-2023 (%):\n", export_growth(trade, 2019, 2023))
    print("\nExports by region, 2023 (USD bn):\n", exports_by_region(trade, 2023))

    report = pd.DataFrame()
    for iso3 in tariffs["iso3"].unique():
        report = report.append({"iso3": iso3, "avg_tariff": average_tariff(tariffs, iso3)},
                               ignore_index=True)
    print("\nAverage tariffs:\n", report)
